### PR TITLE
Add PHP 7.4 image to the Dockerfile generator

### PR DESCRIPTION
**Pull request by owenvoke**
Hoping this works, I can't seem to get the tests to pass locally as it prompts for editor input. It looks like all builds passed on CI, except for one (https://travis-ci.org/github/box-project/box/builds/743917614).

### CODE REVIEW

**Comment by smoench** [comment]
The travis failure is related to https://github.com/JetBrains/phpstorm-stubs/pull/955

**Comment by owenvoke** [comment]
Cheers for the heads up, @smoench 🙂

**Review by theofidry — APPROVED** [review]
LGTM

**Comment by smoench** [comment]
@owenvoke Can you try a rebase? You will get a faster build with GitHub Actions and the phpstorm-stubs issue is resolved

**Comment by owenvoke** [comment]
Sure, I'll rebase it in a couple of minutes.

**Comment by owenvoke** [comment]
Looks like it's still expecting Travis to return a result. I guess that's in the settings?

**Comment by theofidry** [comment]
Yes, I'll remove it

**Comment by theofidry** [comment]
Thank you @owenvoke

**Pull request merged**
