### PR TITLE
Fix OOM-Error in Printer::block

### PR DESCRIPTION
**Pull request by webflo**
Issue #512

### CODE REVIEW

**Comment by webflo** [comment]
The formatting is a bit different from the original, but this only applies to small widths. It should even out on 80 and higher. 0 is a special case. 

The formatting is hard to read. Maybe it makes sense to set it to 80? Not sure about the implications ...

**Comment by webflo** [comment]
Thought about it again, and removed the ``min`` in the constructor to use always the full terminal width. Added COLUMNS to the phpunit.xml fo ensure stable CI testing.

**Review by theofidry — APPROVED** [review]
LGTM; could you apply `make cs` as well?

**Comment by webflo** [comment]
I did ```make cs``` but the diff was huge and it did not catch the wrong indention in my changes. 🤷 

I fixed the files manually.

**Comment by theofidry** [comment]
Yes I suppose. Requirement checker is a kind of library, but when we want to ship it in Box we need to ship an isolated version hence whenever there is a change of the requirement checker we "dump" it again (the isolated version). In itself it's a bit unnecessary noise during the course of a development, but it is necessary to dump it for a release. So you can do `make cs` and revert the dumped requirement checker changes without an issue

**Comment by theofidry** [comment]
Thank you @webflo

**Pull request merged**
