### PR TITLE
Upgrade PHPUnit to 9.5

### PR DESCRIPTION
**Pull request by villfa**

### CODE REVIEW

**Comment by smoench** [comment]
I had some issue with infection after I had to upgrade it to make it runnable with PHP 8 in #508

**Comment by villfa** [comment]
I'm not sure to understand. All tests pass, so what is the issue you refer to?

**Comment by villfa** [comment]
Also, on a side note, @theofidry could you update the settings of the project to remove the build with PHP 7.2 from the list of the required checks?

**Comment by smoench** [comment]
> I'm not sure to understand. All tests pass, so what is the issue you refer to?

Have a look at #510 CI failures

**Comment by theofidry** [comment]
Just a quick heads up as I see several notifications: last week was very busy so sorry if I was holding up anything; I'll hope to catch up a bit tonight

**Review by smoench — APPROVED** [review]

**Comment by theofidry** [comment]
Thank you @villfa

**Pull request merged**
