### PR TITLE
Fixed PHP 8.1 compatibility of the requirement checker

### PR DESCRIPTION
**Pull request by GrahamCampbell**
It looks like https://github.com/box-project/box/pull/557 wasn't enough to fix this. This file needs updating too.

### CODE REVIEW

**Comment by freekmurze** [comment]
This PR seems to fix PHP 8.1 compatibility. 👍 

I'll just create a fork with this fix and use that until it is merged in.

**Comment by GrahamCampbell** [comment]
I am using my fork. ;)

**Comment by Jeckerson** [comment]
@theofidry ping

**Comment by jakzal** [comment]
The build failure:

```
atal error: During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/box/box/vendor/symfony/console/Helper/HelperSet.php:103
#0 /home/runner/work/box/box/vendor/symfony/console/Helper/HelperSet.php(22): KevinGH\Box\{closure}()
```

will probably be fixed by https://github.com/symfony/symfony/pull/42260

**Comment by jakzal** [comment]
The above fix was released in Symfony 4.4.30, 5.3.7, 5.4.0, and 6.0.0.

**Comment by theofidry** [comment]
Thank you. Will update the Symfony dependencies shortly

**Pull request merged**
