### PR TITLE
Add composer.lock

### PR DESCRIPTION
**Pull request by villfa**
@smoench I push the composer.lock I had on my machine since the last time I worked on Box. Hopefully the build should pass with it.

### CODE REVIEW

**Comment by smoench** [comment]
Does it also includes the changes in php-scoper for composer v2?

**Comment by villfa** [comment]
No, it doesn't. It uses php-scoper 0.13.5.
I think we could upgrade it later when the build will be stable.

**Comment by villfa** [comment]
Well there is still a test failing because of composer v2: `make e2e_symfony`
I'm not sure how to fix it yet...

**Comment by smoench** [comment]
Symfony flex needs to be updated to the latest version (1.9.10) for this test case

**Comment by villfa** [comment]
@theofidry the build is green again :)

**Comment by theofidry** [comment]
Thank you!

**Pull request merged**
