### PR TITLE
Allow `$schema` in JSON schema

### PR DESCRIPTION
**Pull request by jrmajor**
Adding `{"$schema": "vendor/humbug/box/res/schema.json"}` to the config file allows PhpStorm to provide completions. However, the `$schema` key is reported as not allowed.

### CODE REVIEW

**Comment by theofidry** [comment]
Thank you very much @jrmajor!

**Comment by danepowell** [comment]
This only works if you've installed Box via Composer in your local project, which you're generally not encouraged (/ can't) do, right?

What's the alternative if you've installed the Phar?

**Comment by theofidry** [comment]
I don't think you have one unfortunately. This would require to publish the schema from an easily downloadable place. Unless adding it to the release actually works, I don't see how it can be done.

Although maybe there is a way to point at the one contained in the PHAR?

**Comment by danepowell** [comment]
`"$schema": "https://raw.githubusercontent.com/box-project/box/main/res/schema.json"` seems to work

Although it's not ideal, since the version is likely to get out of sync with the installed Box version.

**Comment by jrmajor** [comment]
I would suggest referencing the exact version instead of the `main` branch:

```diff
- "$schema": "https://raw.githubusercontent.com/box-project/box/main/res/schema.json"
+ "$schema": "https://raw.githubusercontent.com/box-project/box/4.2.0/res/schema.json"
```

**Pull request merged**
