### PR TITLE
Proposal for documentation site

### PR DESCRIPTION
**Pull request by cristianoc72**
With this commit, I propose to organize the documentation in a site.

I used [Mkdocs](https://www.mkdocs.org/) with [material design theme](https://squidfunk.github.io/mkdocs-material/) with a small customization.
I didn't change the the content of the original documents: I only removed the TOCs, since Mkdocs automatically creates them.
I also added a Github Actions workflow, to deploy the documentation site on Github Pages.

You can get a look to the final result here https://cristianoc72.github.io/box/

Of course, we can change colors, home page etc. Any suggestion is wellcome!

### CODE REVIEW

**Comment by theofidry** [comment]
I had a quick look at the rendering and it looks quite nice!

I would change a couple of things regarding the content, but that's something I can take care of myself as it's probably stuff that need a bit of tinkering.

I'll have a deeper look in the coming week if possible. Is there an easy way to check it out locally? (the rendered version)

**Comment by cristianoc72** [comment]
Yes, sure! Follow these steps:

1.  ensure you have `Python 3` and `pip` installed on your computer:
```bash
python --version
```
```bash
pip --version
```
on Ubuntu:
```bash
python3 --version`
```

2.  install [mkdocs](https://www.mkdocs.org/) and the relative [material theme](https://squidfunk.github.io/mkdocs-material/)
```bash
pip install mkdocs mkdocs-material
```

3.  move into the `box` root directory, then run:
```bash
mkdocs serve
```
Now, point your browser to http://127.0.0.1:8000/box/ .

If you want to inspect the generated html, run:
```bash
mkdocs build
```
The whole site in generated into `site` directory (git ignored).

You can manually deploy the site, too:
```bash
mkdocs gh-deploy
```

**Comment by theofidry** [comment]
Will check it out. I couldn't pay any attention to this PR unfortunately and it's a great shame because I really love the result. I think though I'll have to before releasing Box 4 :)

**Comment by theofidry** [comment]
Thank you again @cristianoc72, finally got it merged :)

I did some slight adjustements to still allow it to be browseable through GitHub as pure markdown, but I don't think it impacts much the website version.

**Comment by theofidry** [comment]
Hm it appears there is some slight differences: the links colors is not correct, will have to figure out why

**Comment by cristianoc72** [comment]
The main css file seems different. I'll investigate it this weekend. It could be a configuration option which has become mandatory in the most recent version of mkdocs materia theme.

**Pull request merged**
